### ISSUE TITLE
This should really be a gist

### ISSUE THREAD

**Issue by smileytechguy** [citrusui/aliases#1]

**Comment by citrusui** [comment]
I've considered making this a Gist, actually. However, Gist does not work well with submodules. My plan is to split up @citrusui/setup into multiple repos, each with one dedicated to a specific purpose (bash, iterm, vscode, atom, git configs). I'm doing this because I have no reason to drop files meant for Linux (`.pantheon`, `.gtk`, etc.) onto, for example, macOS. Ideally, I'd be able to clone citrusui@setup, cd into it, and run setup with args like this **(just an example!):**

`source setup.sh --macos --no-linux --no-sublime`

Besides, you don't get issues and pull requests with Gist -- only forks.

A few other notes:

- I'm not doing this to increase my number of repos. If I could, I would dedicate a branch to each function (vscode, sublime, etc.) but I believe that would cause more headache.
- If this repository every becomes useful to others, (extremely unlikely, seeing as I only have 2 stars from other random people :stuck_out_tongue:) I want to make sure that people can clone and setup each individual repo, if, for example, they don't care about all the other dotfiles and just want settings for vscode.
- This is partly inspired by https://github.com/Homebrew/homebrew-core, although Homebrew doesn't use submodules (probably to reduce the repo size and speed up Git clones).
    - Another note: Homebrew depends on Ruby, which is preinstalled on macOS but not on Linux (usually). I want to make this (these?) setup repos as portable as possible. I thought about just using `curl` or `wget` to fetch additional files, but `curl` isn't preinstalled on Ubuntu and `wget` isn't preinstalled on macOS. While I can't avoid Git just yet, I can avoid the need for `curl` or `wget`. Besides, if you're on GitHub, chances are you have Git or know how to install it :sunglasses:

**Comment by smileytechguy** [comment]
ah, thats cool.  you can use some bash magic to test if `which wget` returns empty or likewise with curl if you wanted to see which had what.

Feel free to check out the dead @smileytechguy/setup and fix it up, it needs prompts
I had them almost done but accidentally deleted the source

**Comment by citrusui** [comment]
No prob. You're right about using `which` for fetching files! I was only thinking about using `curl`/`wget` for setting up stuff. For example, this is how [Meteor](https://www.meteor.com/install) does it:

`curl https://install.meteor.com/ | sh`

Of course, curl isn't yet everywhere so this won't wok out-of-the-box. Besides, this can be a [little insecure.](https://www.seancassidy.me/dont-pipe-to-your-shell.html)

**Comment by citrusui** [comment]
Closing since the majority of it has been implemented (e.g. independent submodules and command line args).

**Comment by smileytechguy** [comment]
👍
